### ISSUE TITLE
Keeping contract ABIs up-to-date

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#110]
## 📚 Context

Anyone can interact with Solidity contracts by means of message calls. These message calls have to be formatted in a such a way that the contract can understand and act upon. Solidity specifies the format of these message calls, as well as events, and errors. What usually happens, however, is that information gets lost when these abstractions get converted into low-level EVM instructions. That is why each Solidity contract is often accompanied by a JSON file which explains their interface in high-level Solidity terms. Libraries like `ethers-rs` use these files, called ABIs, to help developers interact with Solidity contracts, through language-specific bindings.

The problem is that off-chain developers must have the ABIs in order to generate the Rust bindings, and so on-chain developers must keep the ABIs up-to-date with the contracts. Additionally, since these ABIs tend to be quite large, on-chain PRs often get polluted with unnecessarily large diffs. This impacts the productivity of on-chain developers and cleanliness of on-chain PRs.

## ✔️ Solutions

There are several possible solutions which have been raised. IMO, the third solution seems the most sustainable.

1. Create a workflow that automatically updates the ABIs when necessary.

   **Pros:**
   - On-chain developers don't need to update ABIs every time contracts change.

   **Cons:**
   - We'd have to give write permission to a workflow.
   - Commits would come from a strange user, like a bot, with no signature.
   - The developer would depend on the CI to have the artifacts locally.

2. Create a workflow that automatically creates/updates a PR that updates the ABIs.

   **Pros:**
   - Less intrusive than a bot committing directly.
   - On-chain developers don't need to update ABIs every time contracts change.
   - On-chain PRs get much cleaner.

   **Cons:**
   - Off-chain developers would depend on the PR to be merged to have the latest ABIs.
   - A lot of effort would need to be invested in this solution

3. Stop committing ABIs. Let off-chain developers generate them locally. [^1]

   **Pros:**
   - Off-chain developers always have the latest ABIs locally.
   - On-chain developers don't need to update ABIs every time contracts change.
   - On-chain PRs get much cleaner.

   **Cons:**
   - Off-chain developers might need to have more things installed?

[^1]: This can be made seamless for off-chain developers by altering the `offchain/contracts/build.rs` file to run `yarn` and `yarn prepack` in the `onchain/rollups` directory every time something in the `onchain/rollups/contracts` directory changes.

**Comment by tuler** [comment]
I prefer option 3.
offchain uses cargo.
onchain uses npm.
This requires some kind of cross-framework build tool.
Something smart enough so when you do a `cargo build` in the offchain it knows there is a dependency to the `onchain` and trigger the onchain build.
This is a classic problem of inter-package dependency of monorepos.

There is one framework that I'd like to understand more is https://nx.dev. It supposedly supports cross-framework builds, with the [cargo plugin](https://github.com/cammisuli/monodon/tree/main/packages/rust#monodonrust).

**Comment by juztamau5** [comment]
I'm going to propose a novel solution: Generate the ABIs from the bytecode when needed.

We want to preserve the message calls, events, and errors from Solidity. But these can actually be recovered from the bytecode directly using abi-to-sol.

In the current Ultrachess contracts, we depend on Curve, but Curve is compiled from Vyper so all we get is the bytecode. We address that here: https://github.com/Ultrachess/contracts/blob/main/tools/depends/curve/package.sh#L125

**Comment by guidanoli** [comment]
> I'll propose a solution: Generate the ABIs from the bytecode when needed.

Hey, thanks for your contribution! Could you elaborate more on why is generating ABIs from the bytecode favorable to letting `solc` generate it from the source code directly?

**Comment by juztamau5** [comment]
I guess it depends on access to the source. We only use abi-to-sol for Vyper code. If solc can generate interfaces without round-tripping into bytecode then that's probably a better solution.

**Comment by guidanoli** [comment]
> If solc can generate interfaces without round-tripping into bytecode then that's probably a better solution

We use Hardhat and Foundry to interact with our smart contracts, and both frameworks allow us to generate ABIs from Solidity code.
