### ISSUE TITLE
Bump dependencies used by the on-chain tests

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#139]
## 📚 Context

We need to bump the following dependencies used by the on-chain tests:

* [`image-rootfs`](https://github.com/cartesi/image-rootfs/releases/) v0.15.0 :arrow_right: v0.17.0
* [`image-kernel`](https://github.com/cartesi/image-kernel/releases/) v0.14.0 :arrow_right: v0.16.0
* [`machine-emulator-rom`](https://github.com/cartesi/machine-emulator-rom/releases) v0.13.0 :arrow_right: v0.16.0

## 📈 Subtasks

- [ ] Bump versions in [`onchain/rollups/test/foundry/dapp/helper/Dockerfile`](https://github.com/cartesi/rollups/blob/be0ead61c1e0105f5c42e80f79b88f06132dda5f/onchain/rollups/test/foundry/dapp/helper/Dockerfile)
- [ ] Verify whether everything is working as expected.

## :people_holding_hands: Acknowledgements

Thanks, @marcelstanley for spotting this problem. :grin:

**Comment by ZzzzHui** [comment]
The link for `machine-emulator-rom` should be this one  :)
https://github.com/cartesi/machine-emulator-rom/releases
