### ISSUE TITLE
Chose between `actix` and `axum`

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups#152]
## 📚 Context

We are using both `actix` and `axum`, two libraries that do roughly the same thing.

## ✔️ Solution

We should change the code to only use `actix`.

**Comment by torives** [comment]
Isn't this a duplicate of #86?

**Comment by gligneul** [comment]
> Isn't this a duplicate of https://github.com/cartesi/rollups/issues/86?

Yes. Closing this one.
