### ISSUE TITLE
Metrics MVP

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups#17]
## 📚 Context

We need to improve the observability of the Cartesi Node by exposing domain-driven metrics.

## ✔️ Solution

We are going to use Prometheus to add, store, and query metrics in the rollups' services.

## 📈 Subtasks

- [x] Metrics library wrapping over Prometheus (included in the dispatcher issue)
- [x] #18
- [ ] #19
- [ ] #20
- [ ] #21
- [ ] #22
- [ ] #102

**Comment by gligneul** [comment]
Regarding the first item (Metrics library wrapping over Prometheus), I prefer to keep the wrapper slim as possible. It might be a good idea to implement the metrics in the dispatcher first without a wrapper and then create it when we realize what code can be reused.

**Comment by gligneul** [comment]
We reached the MVP with the dispatcher metrics. I will close the epic issue and leave the other issues open.
