### ISSUE TITLE
Improve `genScript.ts`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups#197]
## 📚 Context

The [`genScript.ts`](https://github.com/cartesi/rollups/blob/c56eff125d5446e1c4009fe4dce49d3e614cda4f/onchain/rollups/test/foundry/dapp/helper/genScript.ts) file generates the `gen-proofs.sh` script that is executed by [the Docker image](https://github.com/cartesi/rollups/blob/c56eff125d5446e1c4009fe4dce49d3e614cda4f/onchain/rollups/test/foundry/dapp/helper/Dockerfile).
This script is responsible for running the server manager, feeding inputs, and finishing the epoch.
In between these steps, the script sleeps for some hard-coded number of seconds.
This hinders the productivity of on-chain developers and also isn't guaranteed to work in every machine.

## ✔️ Solution

We can use the [`getEpochStatus`](https://github.com/cartesi/grpc-interfaces/blob/ff2228d5448b63573790d429f9ad3d62ef5361a3/server-manager.proto#L79) entry point to ask the server manager whether a certain input was processed already or is pending. This may not only speed up the proof generation process, but is certainly safer than trusting that each step doesn't take more than some constant period of time.

**Comment by gligneul** [comment]
There isn't a better way. :cry:
