### ISSUE TITLE
Add Rust Clippy to CI

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#25]
## 📚 Context

[Clippy](https://github.com/rust-lang/rust-clippy) is a linter for Rust. We can use it to improve our code quality.

## ✔️ Solution

First, we need to define a sensible configuration for Clippy. We probably can ignore some warnings that don't apply to our code. On the other hand, all warnings that we want to enforce should be considered errors.

Then, we need to fix the existing errors so we can create a new CI workflow that runs Clippy every time. We should evaluate whether it is best to create a new workflow or add Clippy to an existing one.

## 📈 Subtasks

- [x] Configure Clippy
- [x] Fix errors
- [x] Add it to CI

**Comment by marcelstanley** [comment]
Raw report from Clippy: [20230706_clippy_report.txt](https://github.com/cartesi/rollups/files/11972896/20230706_clippy_report.txt)

**Comment by gligneul** [comment]
I did a quick look, and the warnings make sense. We should fix them.

**Comment by marcelstanley** [comment]
Some warnings were deferred to #202

**Comment by marcelstanley** [comment]
Merged to branch `next`
