### ISSUE TITLE
Dispatcher finishes epoch with no inputs

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#84]
## 🙂 Expected behavior

The dispatcher should not ask to finish an epoch when the epoch has no inputs.

## 🫠 Actual behavior

If the epoch time has passed for the first epoch, the dispatcher finishes the epoch even if it doesn't have inputs. Then, when it tries to generate the second epoch, the dispatcher raises the following error:

```
2023-05-31T19:26:25.243757Z  INFO dispatcher::machine::rollups_broker: finishing epoch inputs_sent_count=3
2023-05-31T19:29:01.590675Z  INFO dispatcher::drivers::blockchain: Sending claim `RollupsClaim { epoch_index: 1, epoch_hash: b6e446f15dfe1cd939e0b7c74af4d9c0930f80a2cdcb69196c35445994dc1747, first_index: 0, last_ind
ex: 2 }`
2023-05-31T19:29:01.684224Z  WARN eth_tx_manager::manager: Gas oracle has failed and/or is defaulting to the provider (defaulting).
2023-05-31T19:29:01.766719Z ERROR rollups_dispatcher: Dispatcher stopped: Ok(Err(middleware: (code: 3, message: execution reverted: History: unclaimed inputs, data: Some(String("0x08c379a000000000000000000000000
000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000019486973746f72793a20756e636c61696d656420696e7075747300000000000000")))))
Error: middleware: (code: 3, message: execution reverted: History: unclaimed inputs, data: Some(String("0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000
0000000000000000000000000000019486973746f72793a20756e636c61696d656420696e7075747300000000000000")))
```

## 🧪 Minimal test case

It is possible to reproduce this problem with rollups examples.
First, start the examples (in the 0.9.0 branch), and advance the hardhat time with the following command:

```
curl --data '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":[864010]}' http://localhost:8545
```

Then, send an input and advance the time again using the previous command.

## 🌎 Environment

Rollups 0.9.0

## ✔️ Possible solutions

The following function does not cover the case when the first epoch has no inputs. https://github.com/cartesi/rollups/blob/main/offchain/dispatcher/src/drivers/context.rs#L81

We should fix this issue in the `release/0.9.x` and `main` branches.

**Comment by tuler** [comment]
BTW this fix has a good big impact on cost because it avoids sending a transaction for a dapp that had no inputs since the last epoch.

**Comment by endersonmaia** [comment]
> BTW this fix has a good big impact on cost because it avoids sending a transaction for a dapp that had no inputs since the last epoch.

You're saying that dispatcher won't make claims (sending a transaction) every 24h (current period for DApps we deployed) if there's no inputs since the last claim.

Correct?

If that's the case, our current model of monitoring for claims will not work anymore, and I should disable them (reducing costs a bit) until we have the prometheus metrics available.

**Comment by gligneul** [comment]
> You're saying that dispatcher won't make claims (sending a transaction) every 24h (current period for DApps we deployed) if there's no inputs since the last claim.

This is already expected for 0.9, regardless of this fix. This is considered a bug because this is not being followed for the first epoch.
