### ISSUE TITLE
Disable colored log messages in node

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups#94]
## 📚 Context

By default, some node services print log messages with color, which is problematic because some log aggregators do not parse the color information properly. 

## ✔️ Solution

Disable log colors in all services by default. Then, add a command line option (and env var) that enables the color.

## 📈 Subtasks

Apply the modifications to all services:

- [ ] state server
- [ ] dispatcher
- [ ] advance runner
- [ ] inspect server
- [ ] graphql server
- [ ] host runner

**Comment by tuler** [comment]
Is it configurable?
color is nice for local execution (with sunodo)

**Comment by gligneul** [comment]
I think this could be tackled with other minor format issues. Keeping all modifications in a single issue to improve code reuse will be better. https://github.com/cartesi/rollups/issues/96
